# Generated by Django 5.2.6 on 2025-09-05 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250905_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(default='default account number', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='the supreme boss', max_length=100),
            preserve_default=False,
        ),
    ]
