# Generated by Django 5.2.6 on 2025-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_account_number_alter_customuser_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
