# Generated by Django 5.2.6 on 2025-09-12 17:00

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def assign_permissions_to_groups(apps, schema_editor):
    travellers_group, _ = Group.objects.get_or_create(name='Travellers')
    approvers_group, _ = Group.objects.get_or_create(name='Approvers')
    try:
        can_access_traveller = Permission.objects.get(codename='can_access_traveller_dashboard')
        can_access_approver = Permission.objects.get(codename='can_access_approver_dashboard')
        can_edit_own = Permission.objects.get(codename='can_edit_own_expense')
        can_approve = Permission.objects.get(codename='can_approve_expense')
        can_view_all = Permission.objects.get(codename='can_view_all_expenses')
        travellers_group.permissions.add(can_access_traveller, can_edit_own)
        approvers_group.permissions.add(can_access_approver, can_approve, can_view_all)
        print("Permissions assigned successfully")  
    except Permission.DoesNotExist as e:
        print(f"Permission not found: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_session_data'),
        ('expenses', '0004_expense_is_modified'),
    ]

    operations = [
        migrations.RunPython(
            assign_permissions_to_groups,
        ),
    ]