# Generated by Django 5.2.6 on 2025-09-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_assign_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name'], 'permissions': [('can_access_traveller_dashboard', 'Can access traveller dashboard'), ('can_access_approver_dashboard', 'Can access approver dashboard')]},
        ),
    ]
