# Generated by Django 5.2.6 on 2025-09-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approvers_comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
