# Generated by Django 5.2.6 on 2025-09-09 13:58

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_approvers_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-submission_date']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=datetime.date(2025, 9, 9)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
