# Generated by Django 5.2.6 on 2025-09-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_options_remove_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
