# Generated by Django 5.2.6 on 2025-09-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_is_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-submission_date'], 'permissions': [('can_approve_expense', 'Can approve or reject expenses'), ('can_edit_own_expense', 'Can edit own pending expenses'), ('can_view_all_expenses', 'Can view all expenses')]},
        ),
    ]
